/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {},
    colors: {
      'blue': '#1fb6ff',
      'purple': '#7e5bef',
      'pink': '#ff49db',
      'orange': '#ff7849',
      'yellow': '#ffc82c',
      'gray-dark': '#273444',
      'gray': '#8492a6',
      'gray-light': '#d3dce6',
      'green': '#06d6a0',
      'red': '#ef476f',
      'lacivert': '#25316d',
      'turuncu': '#ff0303',
      'mavi': '#4e6e81',
      'gri': '#ececec',
      'elifBeyaz' : '#FEFBE9',
      'elifYesil' : '#E1EEDD',
      'elifTuruncu' : '#F0A04B',
      'elifSiyah' : '#183A1D',
      'elifGri' : '#dddddd',
      'elifMavi': '#AEBDCA',
      'elifKoyuMavi': '#1c658c',
      'white' : '#ffffff',
      'acikMavi' :'#0466c8',
      'siyah' : '#001233', 
    },
    fontFamily: {
      sans: ['Graphik', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
    },
  },
  plugins: [],
}
