export const CountryFlags = {
    "Afghanistan" : "https://maniacguess.com/static/images/countryFlags/Afghanistan.png",
    "Albania" : "https://maniacguess.com/static/images/countryFlags/Albania.png",
    "Algeria" : "https://maniacguess.com/static/images/countryFlags/Algeria.png",
    "Andorra" : "https://maniacguess.com/static/images/countryFlags/Andorra.png",
    "Angola" : "https://maniacguess.com/static/images/countryFlags/Angola.png",
    "Antigua and Barbuda" : "https://maniacguess.com/static/images/countryFlags/Antigua_and_Barbuda.png",
    "Argentina" : "https://maniacguess.com/static/images/countryFlags/Argentina.png",
    "Armenia" : "https://maniacguess.com/static/images/countryFlags/Armenia.png",
    "Australia" : "https://maniacguess.com/static/images/countryFlags/Australia.png",
    "Austria" : "https://maniacguess.com/static/images/countryFlags/Austria.png",
    "Azerbaijan" : "https://maniacguess.com/static/images/countryFlags/Azerbaijan.png",
    "Bahamas" : "https://maniacguess.com/static/images/countryFlags/Bahamas.png",
    "Bahrain" : "https://maniacguess.com/static/images/countryFlags/Bahrain.png",
    "Bangladesh" : "https://maniacguess.com/static/images/countryFlags/Bangladesh.png",
    "Barbados" : "https://maniacguess.com/static/images/countryFlags/Barbados.png",
    "Belarus" : "https://maniacguess.com/static/images/countryFlags/Belarus.png",
    "Belgium" : "https://maniacguess.com/static/images/countryFlags/Belgium.png",
    "Belize" : "https://maniacguess.com/static/images/countryFlags/Belize.png",
    "Benin" : "https://maniacguess.com/static/images/countryFlags/Benin.png",
    "Bhutan" : "https://maniacguess.com/static/images/countryFlags/Bhutan.png",
    "Bolivia" : "https://maniacguess.com/static/images/countryFlags/Bolivia.png",
    "Bosnia and Herzegovina" : "https://maniacguess.com/static/images/countryFlags/Bosnia_and_Herzegovina.png",
    "Botswana" : "https://maniacguess.com/static/images/countryFlags/Botswana.png",
    "Brazil" : "https://maniacguess.com/static/images/countryFlags/Brazil.png",
    "Brunei " : "https://maniacguess.com/static/images/countryFlags/Brunei_.png",
    "Bulgaria" : "https://maniacguess.com/static/images/countryFlags/Bulgaria.png",
    "Burkina Faso" : "https://maniacguess.com/static/images/countryFlags/Burkina_Faso.png",
    "Burundi" : "https://maniacguess.com/static/images/countryFlags/Burundi.png",
    "Côte d'Ivoire" : "https://maniacguess.com/static/images/countryFlags/Côte_d'Ivoire.png",
    "Cabo Verde" : "https://maniacguess.com/static/images/countryFlags/Cabo_Verde.png",
    "Cambodia" : "https://maniacguess.com/static/images/countryFlags/Cambodia.png",
    "Cameroon" : "https://maniacguess.com/static/images/countryFlags/Cameroon.png",
    "Canada" : "https://maniacguess.com/static/images/countryFlags/Canada.png",
    "CAR" : "https://maniacguess.com/static/images/countryFlags/CAR.png",
    "Chad" : "https://maniacguess.com/static/images/countryFlags/Chad.png",
    "Chile" : "https://maniacguess.com/static/images/countryFlags/Chile.png",
    "China" : "https://maniacguess.com/static/images/countryFlags/China.png",
    "Colombia" : "https://maniacguess.com/static/images/countryFlags/Colombia.png",
    "Comoros" : "https://maniacguess.com/static/images/countryFlags/Comoros.png",
    "Congo" : "https://maniacguess.com/static/images/countryFlags/Congo.png",
    "Costa Rica" : "https://maniacguess.com/static/images/countryFlags/Costa_Rica.png",
    "Croatia" : "https://maniacguess.com/static/images/countryFlags/Croatia.png",
    "Cuba" : "https://maniacguess.com/static/images/countryFlags/Cuba.png",
    "Cyprus" : "https://maniacguess.com/static/images/countryFlags/Cyprus.png",
    "Czechia" : "https://maniacguess.com/static/images/countryFlags/Czechia.png",
    "Denmark" : "https://maniacguess.com/static/images/countryFlags/Denmark.png",
    "Djibouti" : "https://maniacguess.com/static/images/countryFlags/Djibouti.png",
    "Dominica" : "https://maniacguess.com/static/images/countryFlags/Dominica.png",
    "Dominican Republic" : "https://maniacguess.com/static/images/countryFlags/Dominican_Republic.png",
    "DPRK" : "https://maniacguess.com/static/images/countryFlags/DPRK.png",
    "DRC" : "https://maniacguess.com/static/images/countryFlags/DRC.png",
    "Ecuador" : "https://maniacguess.com/static/images/countryFlags/Ecuador.png",
    "Egypt" : "https://maniacguess.com/static/images/countryFlags/Egypt.png",
    "El Salvador" : "https://maniacguess.com/static/images/countryFlags/El_Salvador.png",
    "Equatorial Guinea" : "https://maniacguess.com/static/images/countryFlags/Equatorial_Guinea.png",
    "Eritrea" : "https://maniacguess.com/static/images/countryFlags/Eritrea.png",
    "Estonia" : "https://maniacguess.com/static/images/countryFlags/Estonia.png",
    "Eswatini" : "https://maniacguess.com/static/images/countryFlags/Eswatini.png",
    "Ethiopia" : "https://maniacguess.com/static/images/countryFlags/Ethiopia.png",
    "Fiji" : "https://maniacguess.com/static/images/countryFlags/Fiji.png",
    "Finland" : "https://maniacguess.com/static/images/countryFlags/Finland.png",
    "France" : "https://maniacguess.com/static/images/countryFlags/France.png",
    "Gabon" : "https://maniacguess.com/static/images/countryFlags/Gabon.png",
    "Gambia" : "https://maniacguess.com/static/images/countryFlags/Gambia.png",
    "Georgia" : "https://maniacguess.com/static/images/countryFlags/Georgia.png",
    "Germany" : "https://maniacguess.com/static/images/countryFlags/Germany.png",
    "Ghana" : "https://maniacguess.com/static/images/countryFlags/Ghana.png",
    "Greece" : "https://maniacguess.com/static/images/countryFlags/Greece.png",
    "Grenada" : "https://maniacguess.com/static/images/countryFlags/Grenada.png",
    "Guatemala" : "https://maniacguess.com/static/images/countryFlags/Guatemala.png",
    "Guinea" : "https://maniacguess.com/static/images/countryFlags/Guinea.png",
    "Guinea-Bissau" : "https://maniacguess.com/static/images/countryFlags/Guinea-Bissau.png",
    "Guyana" : "https://maniacguess.com/static/images/countryFlags/Guyana.png",
    "Haiti" : "https://maniacguess.com/static/images/countryFlags/Haiti.png",
    "Holy See" : "https://maniacguess.com/static/images/countryFlags/Holy_See.png",
    "Honduras" : "https://maniacguess.com/static/images/countryFlags/Honduras.png",
    "Hungary" : "https://maniacguess.com/static/images/countryFlags/Hungary.png",
    "Iceland" : "https://maniacguess.com/static/images/countryFlags/Iceland.png",
    "India" : "https://maniacguess.com/static/images/countryFlags/India.png",
    "Indonesia" : "https://maniacguess.com/static/images/countryFlags/Indonesia.png",
    "Iran" : "https://maniacguess.com/static/images/countryFlags/Iran.png",
    "Iraq" : "https://maniacguess.com/static/images/countryFlags/Iraq.png",
    "Ireland" : "https://maniacguess.com/static/images/countryFlags/Ireland.png",
    "Israel" : "https://maniacguess.com/static/images/countryFlags/Israel.png",
    "Italy" : "https://maniacguess.com/static/images/countryFlags/Italy.png",
    "Jamaica" : "https://maniacguess.com/static/images/countryFlags/Jamaica.png",
    "Japan" : "https://maniacguess.com/static/images/countryFlags/Japan.png",
    "Jordan" : "https://maniacguess.com/static/images/countryFlags/Jordan.png",
    "Kazakhstan" : "https://maniacguess.com/static/images/countryFlags/Kazakhstan.png",
    "Kenya" : "https://maniacguess.com/static/images/countryFlags/Kenya.png",
    "Kiribati" : "https://maniacguess.com/static/images/countryFlags/Kiribati.png",
    "Kuwait" : "https://maniacguess.com/static/images/countryFlags/Kuwait.png",
    "Kyrgyzstan" : "https://maniacguess.com/static/images/countryFlags/Kyrgyzstan.png",
    "Laos" : "https://maniacguess.com/static/images/countryFlags/Laos.png",
    "Latvia" : "https://maniacguess.com/static/images/countryFlags/Latvia.png",
    "Lebanon" : "https://maniacguess.com/static/images/countryFlags/Lebanon.png",
    "Lesotho" : "https://maniacguess.com/static/images/countryFlags/Lesotho.png",
    "Liberia" : "https://maniacguess.com/static/images/countryFlags/Liberia.png",
    "Libya" : "https://maniacguess.com/static/images/countryFlags/Libya.png",
    "Liechtenstein" : "https://maniacguess.com/static/images/countryFlags/Liechtenstein.png",
    "Lithuania" : "https://maniacguess.com/static/images/countryFlags/Lithuania.png",
    "Luxembourg" : "https://maniacguess.com/static/images/countryFlags/Luxembourg.png",
    "Madagascar" : "https://maniacguess.com/static/images/countryFlags/Madagascar.png",
    "Malawi" : "https://maniacguess.com/static/images/countryFlags/Malawi.png",
    "Malaysia" : "https://maniacguess.com/static/images/countryFlags/Malaysia.png",
    "Maldives" : "https://maniacguess.com/static/images/countryFlags/Maldives.png",
    "Mali" : "https://maniacguess.com/static/images/countryFlags/Mali.png",
    "Malta" : "https://maniacguess.com/static/images/countryFlags/Malta.png",
    "Marshall Islands" : "https://maniacguess.com/static/images/countryFlags/Marshall_Islands.png",
    "Mauritania" : "https://maniacguess.com/static/images/countryFlags/Mauritania.png",
    "Mauritius" : "https://maniacguess.com/static/images/countryFlags/Mauritius.png",
    "Mexico" : "https://maniacguess.com/static/images/countryFlags/Mexico.png",
    "Micronesia" : "https://maniacguess.com/static/images/countryFlags/Micronesia.png",
    "Moldova" : "https://maniacguess.com/static/images/countryFlags/Moldova.png",
    "Monaco" : "https://maniacguess.com/static/images/countryFlags/Monaco.png",
    "Mongolia" : "https://maniacguess.com/static/images/countryFlags/Mongolia.png",
    "Montenegro" : "https://maniacguess.com/static/images/countryFlags/Montenegro.png",
    "Morocco" : "https://maniacguess.com/static/images/countryFlags/Morocco.png",
    "Mozambique" : "https://maniacguess.com/static/images/countryFlags/Mozambique.png",
    "Myanmar" : "https://maniacguess.com/static/images/countryFlags/Myanmar.png",
    "Namibia" : "https://maniacguess.com/static/images/countryFlags/Namibia.png",
    "Nauru" : "https://maniacguess.com/static/images/countryFlags/Nauru.png",
    "Nepal" : "https://maniacguess.com/static/images/countryFlags/Nepal.png",
    "Netherlands" : "https://maniacguess.com/static/images/countryFlags/Netherlands.png",
    "New Zealand" : "https://maniacguess.com/static/images/countryFlags/New_Zealand.png",
    "Nicaragua" : "https://maniacguess.com/static/images/countryFlags/Nicaragua.png",
    "Niger" : "https://maniacguess.com/static/images/countryFlags/Niger.png",
    "Nigeria" : "https://maniacguess.com/static/images/countryFlags/Nigeria.png",
    "North Macedonia" : "https://maniacguess.com/static/images/countryFlags/North_Macedonia.png",
    "Norway" : "https://maniacguess.com/static/images/countryFlags/Norway.png",
    "Oman" : "https://maniacguess.com/static/images/countryFlags/Oman.png",
    "Pakistan" : "https://maniacguess.com/static/images/countryFlags/Pakistan.png",
    "Palau" : "https://maniacguess.com/static/images/countryFlags/Palau.png",
    "Panama" : "https://maniacguess.com/static/images/countryFlags/Panama.png",
    "Papua New Guinea" : "https://maniacguess.com/static/images/countryFlags/Papua_New_Guinea.png",
    "Paraguay" : "https://maniacguess.com/static/images/countryFlags/Paraguay.png",
    "Peru" : "https://maniacguess.com/static/images/countryFlags/Peru.png",
    "Philippines" : "https://maniacguess.com/static/images/countryFlags/Philippines.png",
    "Poland" : "https://maniacguess.com/static/images/countryFlags/Poland.png",
    "Portugal" : "https://maniacguess.com/static/images/countryFlags/Portugal.png",
    "Qatar" : "https://maniacguess.com/static/images/countryFlags/Qatar.png",
    "Romania" : "https://maniacguess.com/static/images/countryFlags/Romania.png",
    "Russia" : "https://maniacguess.com/static/images/countryFlags/Russia.png",
    "Rwanda" : "https://maniacguess.com/static/images/countryFlags/Rwanda.png",
    "Saint Kitts and Nevis" : "https://maniacguess.com/static/images/countryFlags/Saint_Kitts_and_Nevis.png",
    "Saint Lucia" : "https://maniacguess.com/static/images/countryFlags/Saint_Lucia.png",
    "Samoa" : "https://maniacguess.com/static/images/countryFlags/Samoa.png",
    "San Marino" : "https://maniacguess.com/static/images/countryFlags/San_Marino.png",
    "Sao Tome and Principe" : "https://maniacguess.com/static/images/countryFlags/Sao_Tome_and_Principe.png",
    "Saudi Arabia" : "https://maniacguess.com/static/images/countryFlags/Saudi_Arabia.png",
    "Senegal" : "https://maniacguess.com/static/images/countryFlags/Senegal.png",
    "Serbia" : "https://maniacguess.com/static/images/countryFlags/Serbia.png",
    "Seychelles" : "https://maniacguess.com/static/images/countryFlags/Seychelles.png",
    "Sierra Leone" : "https://maniacguess.com/static/images/countryFlags/Sierra_Leone.png",
    "Singapore" : "https://maniacguess.com/static/images/countryFlags/Singapore.png",
    "Slovakia" : "https://maniacguess.com/static/images/countryFlags/Slovakia.png",
    "Slovenia" : "https://maniacguess.com/static/images/countryFlags/Slovenia.png",
    "Solomon Islands" : "https://maniacguess.com/static/images/countryFlags/Solomon_Islands.png",
    "Somalia" : "https://maniacguess.com/static/images/countryFlags/Somalia.png",
    "South Africa" : "https://maniacguess.com/static/images/countryFlags/South_Africa.png",
    "South Korea" : "https://maniacguess.com/static/images/countryFlags/South_Korea.png",
    "South Sudan" : "https://maniacguess.com/static/images/countryFlags/South_Sudan.png",
    "Spain" : "https://maniacguess.com/static/images/countryFlags/Spain.png",
    "Sri Lanka" : "https://maniacguess.com/static/images/countryFlags/Sri_Lanka.png",
    "St. Vincent Grenadines" : "https://maniacguess.com/static/images/countryFlags/St._Vincent_Grenadines.png",
    "State of Palestine" : "https://maniacguess.com/static/images/countryFlags/State_of_Palestine.png",
    "Sudan" : "https://maniacguess.com/static/images/countryFlags/Sudan.png",
    "Suriname" : "https://maniacguess.com/static/images/countryFlags/Suriname.png",
    "Sweden" : "https://maniacguess.com/static/images/countryFlags/Sweden.png",
    "Switzerland" : "https://maniacguess.com/static/images/countryFlags/Switzerland.png",
    "Syria" : "https://maniacguess.com/static/images/countryFlags/Syria.png",
    "Tajikistan" : "https://maniacguess.com/static/images/countryFlags/Tajikistan.png",
    "Tanzania" : "https://maniacguess.com/static/images/countryFlags/Tanzania.png",
    "Thailand" : "https://maniacguess.com/static/images/countryFlags/Thailand.png",
    "Timor-Leste" : "https://maniacguess.com/static/images/countryFlags/Timor-Leste.png",
    "Togo" : "https://maniacguess.com/static/images/countryFlags/Togo.png",
    "Tonga" : "https://maniacguess.com/static/images/countryFlags/Tonga.png",
    "Trinidad and Tobago" : "https://maniacguess.com/static/images/countryFlags/Trinidad_and_Tobago.png",
    "Tunisia" : "https://maniacguess.com/static/images/countryFlags/Tunisia.png",
    "Turkey" : "https://maniacguess.com/static/images/countryFlags/Turkey.png",
    "Turkmenistan" : "https://maniacguess.com/static/images/countryFlags/Turkmenistan.png",
    "Tuvalu" : "https://maniacguess.com/static/images/countryFlags/Tuvalu.png",
    "U.A.E." : "https://maniacguess.com/static/images/countryFlags/U.A.E..png",
    "U.K." : "https://maniacguess.com/static/images/countryFlags/U.K..png",
    "United States" : "https://maniacguess.com/static/images/countryFlags/U.S..png",
    "Uganda" : "https://maniacguess.com/static/images/countryFlags/Uganda.png",
    "Ukraine" : "https://maniacguess.com/static/images/countryFlags/Ukraine.png",
    "Uruguay" : "https://maniacguess.com/static/images/countryFlags/Uruguay.png",
    "Uzbekistan" : "https://maniacguess.com/static/images/countryFlags/Uzbekistan.png",
    "Vanuatu" : "https://maniacguess.com/static/images/countryFlags/Vanuatu.png",
    "Venezuela" : "https://maniacguess.com/static/images/countryFlags/Venezuela.png",
    "Vietnam" : "https://maniacguess.com/static/images/countryFlags/Vietnam.png",
    "Yemen" : "https://maniacguess.com/static/images/countryFlags/Yemen.png",
    "Zambia" : "https://maniacguess.com/static/images/countryFlags/Zambia.png",
    "Zimbabwe" : "https://maniacguess.com/static/images/countryFlags/Zimbabwe.png"
}